scripts {
  AOESW {
    AOSQ_calibrations_daytime {
      scriptClass = aoesw.DaytimeCalibration
    }
    AOSQ_calibrations_onsky {
      scriptClass = aoesw.OnskyCalibration
    }
    AOSQ_startup {
      scriptClass = aoesw.Startup
    }
    AOSQ_mcao {
      scriptClass = aoesw.Mcao
    }
    LGSF_observing {
      scriptClass = aoesw.lgsfObserving
    }
  }
}